(define (problem p5)
    (:domain railwayd)

    (:objects
        t1 t2 t3 t4 t5 t6 - train
        p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 - railroad-point
        p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 - railroad-point
        broad meter - rail-type
    )

    (:init
        ;; Connected roads
        (connected-road p0 p1)
        (connected-road p1 p0)
        (connected-road p1 p2)
        (connected-road p2 p1)
        (connected-road p3 p4)
        (connected-road p4 p3)
        (connected-road p4 p5)
        (connected-road p5 p4)
        (connected-road p5 p6)
        (connected-road p6 p5)
        (connected-road p7 p8)
        (connected-road p8 p7)
        (connected-road p8 p9)
        (connected-road p9 p8)
        (connected-road p10 p11)
        (connected-road p11 p10)
        (connected-road p11 p12)
        (connected-road p12 p11)
        (connected-road p13 p14)
        (connected-road p14 p13)
        (connected-road p14 p15)
        (connected-road p15 p14)
        (connected-road p15 p16)
        (connected-road p16 p15)
        (connected-road p16 p17)
        (connected-road p17 p16)
        (connected-road p17 p18)
        (connected-road p18 p17)
        (connected-road p19 p20)
        (connected-road p20 p19)
        (connected-road p20 p21)
        (connected-road p21 p20)
        (connected-road p21 p22)
        (connected-road p22 p21)
        (connected-road p22 p23)
        (connected-road p23 p22)
        (connected-road p1 p24)
        (connected-road p24 p1)
        (connected-road p8 p25)
        (connected-road p25 p8)
        (connected-road p17 p26)
        (connected-road p26 p17)
        (connected-road p25 p27)
        (connected-road p27 p25)
        (connected-road p23 p28)
        (connected-road p28 p23)
        (connected-road p17 p29)
        (connected-road p29 p17)

        ;; Not-connected roads
        (not-connected-road p24 p4)
        (not-connected-road p4 p24)
        (not-connected-road p20 p26)
        (not-connected-road p26 p20)
        (not-connected-road p25 p11)
        (not-connected-road p11 p25)

        ;; Accessible roads
        (accessible-road p0 p1)
        (accessible-road p1 p0)
        (accessible-road p1 p2)
        (accessible-road p2 p1)
        (accessible-road p3 p4)
        (accessible-road p4 p3)
        (accessible-road p4 p5)
        (accessible-road p5 p4)
        (accessible-road p5 p6)
        (accessible-road p6 p5)
        (accessible-road p7 p8)
        (accessible-road p8 p7)
        (accessible-road p8 p9)
        (accessible-road p9 p8)
        (accessible-road p10 p11)
        (accessible-road p11 p10)
        (accessible-road p11 p12)
        (accessible-road p12 p11)
        (accessible-road p13 p14)
        (accessible-road p14 p13)
        (accessible-road p14 p15)
        (accessible-road p15 p14)
        (accessible-road p15 p16)
        (accessible-road p16 p15)
        (accessible-road p16 p17)
        (accessible-road p17 p16)
        (accessible-road p17 p18)
        (accessible-road p18 p17)
        (accessible-road p19 p20)
        (accessible-road p20 p19)
        (accessible-road p20 p21)
        (accessible-road p21 p20)
        (accessible-road p21 p22)
        (accessible-road p22 p21)
        (accessible-road p22 p23)
        (accessible-road p23 p22)
        (accessible-road p1 p24)
        (accessible-road p24 p1)
        (accessible-road p4 p24)
        (accessible-road p24 p4)
        (accessible-road p8 p25)
        (accessible-road p25 p8)
        (accessible-road p11 p25)
        (accessible-road p25 p11)
        (accessible-road p17 p26)
        (accessible-road p26 p17)
        (accessible-road p20 p26)
        (accessible-road p26 p20)
        (accessible-road p25 p27)
        (accessible-road p27 p25)
        (accessible-road p23 p28)
        (accessible-road p28 p23)
        (accessible-road p17 p29)
        (accessible-road p29 p17)

        ;; Railroad types
        (railroad-type p0 p1 broad)
        (railroad-type p1 p0 broad)
        (railroad-type p1 p2 broad)
        (railroad-type p2 p1 broad)
        (railroad-type p3 p4 broad)
        (railroad-type p4 p3 broad)
        (railroad-type p4 p5 broad)
        (railroad-type p5 p4 broad)
        (railroad-type p5 p6 broad)
        (railroad-type p6 p5 broad)
        (railroad-type p7 p8 meter)
        (railroad-type p8 p7 meter)
        (railroad-type p8 p9 meter)
        (railroad-type p9 p8 meter)
        (railroad-type p10 p11 broad)
        (railroad-type p11 p10 broad)
        (railroad-type p11 p12 broad)
        (railroad-type p12 p11 broad)
        (railroad-type p13 p14 broad)
        (railroad-type p14 p13 broad)
        (railroad-type p14 p15 broad)
        (railroad-type p15 p14 broad)
        (railroad-type p15 p16 broad)
        (railroad-type p16 p15 broad)
        (railroad-type p16 p17 broad)
        (railroad-type p17 p16 broad)
        (railroad-type p17 p18 broad)
        (railroad-type p18 p17 broad)
        (railroad-type p19 p20 meter)
        (railroad-type p20 p19 meter)
        (railroad-type p20 p21 meter)
        (railroad-type p21 p20 meter)
        (railroad-type p21 p22 meter)
        (railroad-type p22 p21 meter)
        (railroad-type p22 p23 meter)
        (railroad-type p23 p22 meter)
        (railroad-type p1 p24 broad)
        (railroad-type p24 p1 broad)
        (railroad-type p1 p24 meter)
        (railroad-type p24 p1 meter)
        (railroad-type p4 p24 broad)
        (railroad-type p24 p4 broad)
        (railroad-type p4 p24 meter)
        (railroad-type p24 p4 meter)
        (railroad-type p8 p25 broad)
        (railroad-type p25 p8 broad)
        (railroad-type p8 p25 meter)
        (railroad-type p25 p8 meter)
        (railroad-type p11 p25 broad)
        (railroad-type p25 p11 broad)
        (railroad-type p11 p25 meter)
        (railroad-type p25 p11 meter)
        (railroad-type p17 p26 broad)
        (railroad-type p26 p17 broad)
        (railroad-type p17 p26 meter)
        (railroad-type p26 p17 meter)
        (railroad-type p20 p26 broad)
        (railroad-type p26 p20 broad)
        (railroad-type p20 p26 meter)
        (railroad-type p26 p20 meter)
        (railroad-type p25 p27 broad)
        (railroad-type p27 p25 broad)
        (railroad-type p25 p27 meter)
        (railroad-type p27 p25 meter)
        (railroad-type p23 p28 broad)
        (railroad-type p28 p23 broad)
        (railroad-type p23 p28 meter)
        (railroad-type p28 p23 meter)
        (railroad-type p17 p29 broad)
        (railroad-type p29 p17 broad)
        (railroad-type p17 p29 meter)
        (railroad-type p29 p17 meter)

        ;; Train types
        (train-type t1 broad)
        (train-type t2 broad)
        (train-type t3 meter)
        (train-type t4 broad)
        (train-type t5 broad)
        (train-type t6 meter)

        ;; Turnout points
        (turnout-point p24)
        (turnout-point p25)
        (turnout-point p26)

        ;; Turnout alternatives
        (alternative-points p24 p1 p4)
        (alternative-points p24 p4 p1)
        (alternative-points p25 p8 p11)
        (alternative-points p25 p11 p8)
        (alternative-points p26 p17 p20)
        (alternative-points p26 p20 p17)

        ;; Train locations
        (train-at t1 p0)
        (not-free-point p0)
        (train-at t2 p3)
        (not-free-point p3)
        (train-at t3 p7)
        (not-free-point p7)
        (train-at t4 p10)
        (not-free-point p10)
        (train-at t5 p13)
        (not-free-point p13)
        (train-at t6 p19)
        (not-free-point p19)

        ;; Free points
        (free-point p1)
        (free-point p2)
        (free-point p4)
        (free-point p5)
        (free-point p6)
        (free-point p8)
        (free-point p9)
        (free-point p11)
        (free-point p12)
        (free-point p14)
        (free-point p15)
        (free-point p16)
        (free-point p17)
        (free-point p18)
        (free-point p20)
        (free-point p21)
        (free-point p22)
        (free-point p23)
        (free-point p24)
        (free-point p25)
        (free-point p26)
        (free-point p27)
        (free-point p28)
        (free-point p29)

        ;; Not-blocked-track
        (not-blocked-track p0 p1)
        (not-blocked-track p1 p0)
        (not-blocked-track p1 p2)
        (not-blocked-track p2 p1)
        (not-blocked-track p3 p4)
        (not-blocked-track p4 p3)
        (not-blocked-track p4 p5)
        (not-blocked-track p5 p4)
        (not-blocked-track p5 p6)
        (not-blocked-track p6 p5)
        (not-blocked-track p7 p8)
        (not-blocked-track p8 p7)
        (not-blocked-track p8 p9)
        (not-blocked-track p9 p8)
        (not-blocked-track p10 p11)
        (not-blocked-track p11 p10)
        (not-blocked-track p11 p12)
        (not-blocked-track p12 p11)
        (not-blocked-track p13 p14)
        (not-blocked-track p14 p13)
        (not-blocked-track p14 p15)
        (not-blocked-track p15 p14)
        (not-blocked-track p15 p16)
        (not-blocked-track p16 p15)
        (not-blocked-track p16 p17)
        (not-blocked-track p17 p16)
        (not-blocked-track p17 p18)
        (not-blocked-track p18 p17)
        (not-blocked-track p19 p20)
        (not-blocked-track p20 p19)
        (not-blocked-track p20 p21)
        (not-blocked-track p21 p20)
        (not-blocked-track p21 p22)
        (not-blocked-track p22 p21)
        (not-blocked-track p22 p23)
        (not-blocked-track p23 p22)
        (not-blocked-track p1 p24)
        (not-blocked-track p24 p1)
        (not-blocked-track p4 p24)
        (not-blocked-track p24 p4)
        (not-blocked-track p8 p25)
        (not-blocked-track p25 p8)
        (not-blocked-track p11 p25)
        (not-blocked-track p25 p11)
        (not-blocked-track p17 p26)
        (not-blocked-track p26 p17)
        (not-blocked-track p20 p26)
        (not-blocked-track p26 p20)
        (not-blocked-track p25 p27)
        (not-blocked-track p27 p25)
        (not-blocked-track p23 p28)
        (not-blocked-track p28 p23)
        (not-blocked-track p17 p29)
        (not-blocked-track p29 p17)

        ;; Not-train-blocked-at
        (not-train-blocked-at t1 p0)
        (not-train-blocked-at t1 p1)
        (not-train-blocked-at t1 p2)
        (not-train-blocked-at t2 p3)
        (not-train-blocked-at t2 p4)
        (not-train-blocked-at t2 p5)
        (not-train-blocked-at t2 p6)
        (not-train-blocked-at t3 p7)
        (not-train-blocked-at t3 p8)
        (not-train-blocked-at t3 p9)
        (not-train-blocked-at t4 p10)
        (not-train-blocked-at t4 p11)
        (not-train-blocked-at t4 p12)
        (not-train-blocked-at t5 p13)
        (not-train-blocked-at t5 p14)
        (not-train-blocked-at t5 p15)
        (not-train-blocked-at t5 p16)
        (not-train-blocked-at t5 p17)
        (not-train-blocked-at t5 p18)
        (not-train-blocked-at t6 p19)
        (not-train-blocked-at t6 p20)
        (not-train-blocked-at t6 p21)
        (not-train-blocked-at t6 p22)
        (not-train-blocked-at t6 p23)

        ;; Boarding points
        (boarding-point t1 p1)
        (boarding-point t2 p4)
        (boarding-point t3 p8)
        (boarding-point t4 p11)
        (boarding-point t5 p17)
        (boarding-point t6 p20)

        ;; Train speeds
        (= (train-speed t1) 1.0)
        (= (train-speed t2) 1.0)
        (= (train-speed t3) 1.0)
        (= (train-speed t4) 1.0)
        (= (train-speed t5) 1.0)
        (= (train-speed t6) 1.0)

        ;; Road distances
        (= (road-distance p0 p1) 10)
        (= (road-distance p1 p0) 10)
        (= (road-distance p1 p2) 7)
        (= (road-distance p2 p1) 7)
        (= (road-distance p3 p4) 10)
        (= (road-distance p4 p3) 10)
        (= (road-distance p4 p5) 5)
        (= (road-distance p5 p4) 5)
        (= (road-distance p5 p6) 10)
        (= (road-distance p6 p5) 10)
        (= (road-distance p7 p8) 5)
        (= (road-distance p8 p7) 5)
        (= (road-distance p8 p9) 5)
        (= (road-distance p9 p8) 5)
        (= (road-distance p10 p11) 9)
        (= (road-distance p11 p10) 9)
        (= (road-distance p11 p12) 6)
        (= (road-distance p12 p11) 6)
        (= (road-distance p13 p14) 9)
        (= (road-distance p14 p13) 9)
        (= (road-distance p14 p15) 7)
        (= (road-distance p15 p14) 7)
        (= (road-distance p15 p16) 5)
        (= (road-distance p16 p15) 5)
        (= (road-distance p16 p17) 6)
        (= (road-distance p17 p16) 6)
        (= (road-distance p17 p18) 10)
        (= (road-distance p18 p17) 10)
        (= (road-distance p19 p20) 6)
        (= (road-distance p20 p19) 6)
        (= (road-distance p20 p21) 6)
        (= (road-distance p21 p20) 6)
        (= (road-distance p21 p22) 7)
        (= (road-distance p22 p21) 7)
        (= (road-distance p22 p23) 5)
        (= (road-distance p23 p22) 5)
        (= (road-distance p1 p24) 8)
        (= (road-distance p24 p1) 8)
        (= (road-distance p4 p24) 5)
        (= (road-distance p24 p4) 5)
        (= (road-distance p8 p25) 7)
        (= (road-distance p25 p8) 7)
        (= (road-distance p11 p25) 7)
        (= (road-distance p25 p11) 7)
        (= (road-distance p17 p26) 9)
        (= (road-distance p26 p17) 9)
        (= (road-distance p20 p26) 7)
        (= (road-distance p26 p20) 7)
        (= (road-distance p25 p27) 5)
        (= (road-distance p27 p25) 5)
        (= (road-distance p23 p28) 8)
        (= (road-distance p28 p23) 8)
        (= (road-distance p17 p29) 5)
        (= (road-distance p29 p17) 5)

        ;; Board times
        (= (board-time t1 p1) 1)
        (= (board-time t2 p4) 1)
        (= (board-time t3 p8) 1)
        (= (board-time t4 p11) 1)
        (= (board-time t5 p17) 1)
        (= (board-time t6 p20) 1)

        ;; Turnout time
        (= (turnout-time) 1)
    )

    (:goal (and
        (train-at t1 p2)
        (train-at t2 p6)
        (train-at t3 p9)
        (train-at t4 p12)
        (train-at t5 p18)
        (train-at t6 p23)
        (board-passengers t1 p1)
        (board-passengers t2 p4)
        (board-passengers t3 p8)
        (board-passengers t4 p11)
        (board-passengers t5 p17)
        (board-passengers t6 p20)
    ))

    (:metric minimize (total-time))
)