(define (problem p6)
    (:domain railwayd)

    (:objects
        t1 t2 t3 t4 t5 t6 t7 t8 - train
        p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 - railroad-point
        p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30 p31 p32 p33 p34 p35 p36 p37 p38 p39 - railroad-point
        broad meter - rail-type
    )

    (:init
        ;; Connected roads
        (connected-road p0 p1)
        (connected-road p1 p0)
        (connected-road p1 p2)
        (connected-road p2 p1)
        (connected-road p3 p4)
        (connected-road p4 p3)
        (connected-road p4 p5)
        (connected-road p5 p4)
        (connected-road p5 p6)
        (connected-road p6 p5)
        (connected-road p7 p8)
        (connected-road p8 p7)
        (connected-road p8 p9)
        (connected-road p9 p8)
        (connected-road p10 p11)
        (connected-road p11 p10)
        (connected-road p11 p12)
        (connected-road p12 p11)
        (connected-road p13 p14)
        (connected-road p14 p13)
        (connected-road p14 p15)
        (connected-road p15 p14)
        (connected-road p15 p16)
        (connected-road p16 p15)
        (connected-road p16 p17)
        (connected-road p17 p16)
        (connected-road p17 p18)
        (connected-road p18 p17)
        (connected-road p19 p20)
        (connected-road p20 p19)
        (connected-road p20 p21)
        (connected-road p21 p20)
        (connected-road p21 p22)
        (connected-road p22 p21)
        (connected-road p22 p23)
        (connected-road p23 p22)
        (connected-road p24 p25)
        (connected-road p25 p24)
        (connected-road p25 p26)
        (connected-road p26 p25)
        (connected-road p27 p28)
        (connected-road p28 p27)
        (connected-road p28 p29)
        (connected-road p29 p28)
        (connected-road p29 p30)
        (connected-road p30 p29)
        (connected-road p30 p31)
        (connected-road p31 p30)
        (connected-road p31 p32)
        (connected-road p32 p31)
        (connected-road p1 p33)
        (connected-road p33 p1)
        (connected-road p8 p34)
        (connected-road p34 p8)
        (connected-road p17 p35)
        (connected-road p35 p17)
        (connected-road p25 p36)
        (connected-road p36 p25)
        (connected-road p14 p37)
        (connected-road p37 p14)
        (connected-road p5 p38)
        (connected-road p38 p5)
        (connected-road p6 p39)
        (connected-road p39 p6)

        ;; Not-connected roads
        (not-connected-road p20 p35)
        (not-connected-road p35 p20)
        (not-connected-road p34 p11)
        (not-connected-road p11 p34)
        (not-connected-road p4 p33)
        (not-connected-road p33 p4)
        (not-connected-road p36 p30)
        (not-connected-road p30 p36)

        ;; Accessible roads
        (accessible-road p0 p1)
        (accessible-road p1 p0)
        (accessible-road p1 p2)
        (accessible-road p2 p1)
        (accessible-road p3 p4)
        (accessible-road p4 p3)
        (accessible-road p4 p5)
        (accessible-road p5 p4)
        (accessible-road p5 p6)
        (accessible-road p6 p5)
        (accessible-road p7 p8)
        (accessible-road p8 p7)
        (accessible-road p8 p9)
        (accessible-road p9 p8)
        (accessible-road p10 p11)
        (accessible-road p11 p10)
        (accessible-road p11 p12)
        (accessible-road p12 p11)
        (accessible-road p13 p14)
        (accessible-road p14 p13)
        (accessible-road p14 p15)
        (accessible-road p15 p14)
        (accessible-road p15 p16)
        (accessible-road p16 p15)
        (accessible-road p16 p17)
        (accessible-road p17 p16)
        (accessible-road p17 p18)
        (accessible-road p18 p17)
        (accessible-road p19 p20)
        (accessible-road p20 p19)
        (accessible-road p20 p21)
        (accessible-road p21 p20)
        (accessible-road p21 p22)
        (accessible-road p22 p21)
        (accessible-road p22 p23)
        (accessible-road p23 p22)
        (accessible-road p24 p25)
        (accessible-road p25 p24)
        (accessible-road p25 p26)
        (accessible-road p26 p25)
        (accessible-road p27 p28)
        (accessible-road p28 p27)
        (accessible-road p28 p29)
        (accessible-road p29 p28)
        (accessible-road p29 p30)
        (accessible-road p30 p29)
        (accessible-road p30 p31)
        (accessible-road p31 p30)
        (accessible-road p31 p32)
        (accessible-road p32 p31)
        (accessible-road p1 p33)
        (accessible-road p33 p1)
        (accessible-road p4 p33)
        (accessible-road p33 p4)
        (accessible-road p8 p34)
        (accessible-road p34 p8)
        (accessible-road p11 p34)
        (accessible-road p34 p11)
        (accessible-road p17 p35)
        (accessible-road p35 p17)
        (accessible-road p20 p35)
        (accessible-road p35 p20)
        (accessible-road p25 p36)
        (accessible-road p36 p25)
        (accessible-road p30 p36)
        (accessible-road p36 p30)
        (accessible-road p14 p37)
        (accessible-road p37 p14)
        (accessible-road p5 p38)
        (accessible-road p38 p5)
        (accessible-road p6 p39)
        (accessible-road p39 p6)

        ;; Railroad types
        (railroad-type p0 p1 broad)
        (railroad-type p1 p0 broad)
        (railroad-type p1 p2 broad)
        (railroad-type p2 p1 broad)
        (railroad-type p3 p4 broad)
        (railroad-type p4 p3 broad)
        (railroad-type p4 p5 broad)
        (railroad-type p5 p4 broad)
        (railroad-type p5 p6 broad)
        (railroad-type p6 p5 broad)
        (railroad-type p7 p8 meter)
        (railroad-type p8 p7 meter)
        (railroad-type p8 p9 meter)
        (railroad-type p9 p8 meter)
        (railroad-type p10 p11 broad)
        (railroad-type p11 p10 broad)
        (railroad-type p11 p12 broad)
        (railroad-type p12 p11 broad)
        (railroad-type p13 p14 broad)
        (railroad-type p14 p13 broad)
        (railroad-type p14 p15 broad)
        (railroad-type p15 p14 broad)
        (railroad-type p15 p16 broad)
        (railroad-type p16 p15 broad)
        (railroad-type p16 p17 broad)
        (railroad-type p17 p16 broad)
        (railroad-type p17 p18 broad)
        (railroad-type p18 p17 broad)
        (railroad-type p19 p20 meter)
        (railroad-type p20 p19 meter)
        (railroad-type p20 p21 meter)
        (railroad-type p21 p20 meter)
        (railroad-type p21 p22 meter)
        (railroad-type p22 p21 meter)
        (railroad-type p22 p23 meter)
        (railroad-type p23 p22 meter)
        (railroad-type p24 p25 meter)
        (railroad-type p25 p24 meter)
        (railroad-type p25 p26 meter)
        (railroad-type p26 p25 meter)
        (railroad-type p27 p28 broad)
        (railroad-type p28 p27 broad)
        (railroad-type p28 p29 broad)
        (railroad-type p29 p28 broad)
        (railroad-type p29 p30 broad)
        (railroad-type p30 p29 broad)
        (railroad-type p30 p31 broad)
        (railroad-type p31 p30 broad)
        (railroad-type p31 p32 broad)
        (railroad-type p32 p31 broad)
        (railroad-type p1 p33 broad)
        (railroad-type p33 p1 broad)
        (railroad-type p1 p33 meter)
        (railroad-type p33 p1 meter)
        (railroad-type p4 p33 broad)
        (railroad-type p33 p4 broad)
        (railroad-type p4 p33 meter)
        (railroad-type p33 p4 meter)
        (railroad-type p8 p34 broad)
        (railroad-type p34 p8 broad)
        (railroad-type p8 p34 meter)
        (railroad-type p34 p8 meter)
        (railroad-type p11 p34 broad)
        (railroad-type p34 p11 broad)
        (railroad-type p11 p34 meter)
        (railroad-type p34 p11 meter)
        (railroad-type p17 p35 broad)
        (railroad-type p35 p17 broad)
        (railroad-type p17 p35 meter)
        (railroad-type p35 p17 meter)
        (railroad-type p20 p35 broad)
        (railroad-type p35 p20 broad)
        (railroad-type p20 p35 meter)
        (railroad-type p35 p20 meter)
        (railroad-type p25 p36 broad)
        (railroad-type p36 p25 broad)
        (railroad-type p25 p36 meter)
        (railroad-type p36 p25 meter)
        (railroad-type p30 p36 broad)
        (railroad-type p36 p30 broad)
        (railroad-type p30 p36 meter)
        (railroad-type p36 p30 meter)
        (railroad-type p14 p37 broad)
        (railroad-type p37 p14 broad)
        (railroad-type p14 p37 meter)
        (railroad-type p37 p14 meter)
        (railroad-type p5 p38 broad)
        (railroad-type p38 p5 broad)
        (railroad-type p5 p38 meter)
        (railroad-type p38 p5 meter)
        (railroad-type p6 p39 broad)
        (railroad-type p39 p6 broad)
        (railroad-type p6 p39 meter)
        (railroad-type p39 p6 meter)

        ;; Train types
        (train-type t1 broad)
        (train-type t2 broad)
        (train-type t3 meter)
        (train-type t4 broad)
        (train-type t5 broad)
        (train-type t6 meter)
        (train-type t7 meter)
        (train-type t8 broad)

        ;; Turnout points
        (turnout-point p33)
        (turnout-point p34)
        (turnout-point p35)
        (turnout-point p36)

        ;; Turnout alternatives
        (alternative-points p33 p1 p4)
        (alternative-points p33 p4 p1)
        (alternative-points p34 p8 p11)
        (alternative-points p34 p11 p8)
        (alternative-points p35 p17 p20)
        (alternative-points p35 p20 p17)
        (alternative-points p36 p25 p30)
        (alternative-points p36 p30 p25)

        ;; Train locations
        (train-at t1 p0)
        (not-free-point p0)
        (train-at t2 p3)
        (not-free-point p3)
        (train-at t3 p7)
        (not-free-point p7)
        (train-at t4 p10)
        (not-free-point p10)
        (train-at t5 p13)
        (not-free-point p13)
        (train-at t6 p19)
        (not-free-point p19)
        (train-at t7 p24)
        (not-free-point p24)
        (train-at t8 p27)
        (not-free-point p27)

        ;; Free points
        (free-point p1)
        (free-point p2)
        (free-point p4)
        (free-point p5)
        (free-point p6)
        (free-point p8)
        (free-point p9)
        (free-point p11)
        (free-point p12)
        (free-point p14)
        (free-point p15)
        (free-point p16)
        (free-point p17)
        (free-point p18)
        (free-point p20)
        (free-point p21)
        (free-point p22)
        (free-point p23)
        (free-point p25)
        (free-point p26)
        (free-point p28)
        (free-point p29)
        (free-point p30)
        (free-point p31)
        (free-point p32)
        (free-point p33)
        (free-point p34)
        (free-point p35)
        (free-point p36)
        (free-point p37)
        (free-point p38)
        (free-point p39)

        ;; Not-blocked-track
        (not-blocked-track p0 p1)
        (not-blocked-track p1 p0)
        (not-blocked-track p1 p2)
        (not-blocked-track p2 p1)
        (not-blocked-track p3 p4)
        (not-blocked-track p4 p3)
        (not-blocked-track p4 p5)
        (not-blocked-track p5 p4)
        (not-blocked-track p5 p6)
        (not-blocked-track p6 p5)
        (not-blocked-track p7 p8)
        (not-blocked-track p8 p7)
        (not-blocked-track p8 p9)
        (not-blocked-track p9 p8)
        (not-blocked-track p10 p11)
        (not-blocked-track p11 p10)
        (not-blocked-track p11 p12)
        (not-blocked-track p12 p11)
        (not-blocked-track p13 p14)
        (not-blocked-track p14 p13)
        (not-blocked-track p14 p15)
        (not-blocked-track p15 p14)
        (not-blocked-track p15 p16)
        (not-blocked-track p16 p15)
        (not-blocked-track p16 p17)
        (not-blocked-track p17 p16)
        (not-blocked-track p17 p18)
        (not-blocked-track p18 p17)
        (not-blocked-track p19 p20)
        (not-blocked-track p20 p19)
        (not-blocked-track p20 p21)
        (not-blocked-track p21 p20)
        (not-blocked-track p21 p22)
        (not-blocked-track p22 p21)
        (not-blocked-track p22 p23)
        (not-blocked-track p23 p22)
        (not-blocked-track p24 p25)
        (not-blocked-track p25 p24)
        (not-blocked-track p25 p26)
        (not-blocked-track p26 p25)
        (not-blocked-track p27 p28)
        (not-blocked-track p28 p27)
        (not-blocked-track p28 p29)
        (not-blocked-track p29 p28)
        (not-blocked-track p29 p30)
        (not-blocked-track p30 p29)
        (not-blocked-track p30 p31)
        (not-blocked-track p31 p30)
        (not-blocked-track p31 p32)
        (not-blocked-track p32 p31)
        (not-blocked-track p1 p33)
        (not-blocked-track p33 p1)
        (not-blocked-track p4 p33)
        (not-blocked-track p33 p4)
        (not-blocked-track p8 p34)
        (not-blocked-track p34 p8)
        (not-blocked-track p11 p34)
        (not-blocked-track p34 p11)
        (not-blocked-track p17 p35)
        (not-blocked-track p35 p17)
        (not-blocked-track p20 p35)
        (not-blocked-track p35 p20)
        (not-blocked-track p25 p36)
        (not-blocked-track p36 p25)
        (not-blocked-track p30 p36)
        (not-blocked-track p36 p30)
        (not-blocked-track p14 p37)
        (not-blocked-track p37 p14)
        (not-blocked-track p5 p38)
        (not-blocked-track p38 p5)
        (not-blocked-track p6 p39)
        (not-blocked-track p39 p6)

        ;; Not-train-blocked-at
        (not-train-blocked-at t1 p0)
        (not-train-blocked-at t1 p1)
        (not-train-blocked-at t1 p2)
        (not-train-blocked-at t2 p3)
        (not-train-blocked-at t2 p4)
        (not-train-blocked-at t2 p5)
        (not-train-blocked-at t2 p6)
        (not-train-blocked-at t3 p7)
        (not-train-blocked-at t3 p8)
        (not-train-blocked-at t3 p9)
        (not-train-blocked-at t4 p10)
        (not-train-blocked-at t4 p11)
        (not-train-blocked-at t4 p12)
        (not-train-blocked-at t5 p13)
        (not-train-blocked-at t5 p14)
        (not-train-blocked-at t5 p15)
        (not-train-blocked-at t5 p16)
        (not-train-blocked-at t5 p17)
        (not-train-blocked-at t5 p18)
        (not-train-blocked-at t6 p19)
        (not-train-blocked-at t6 p20)
        (not-train-blocked-at t6 p21)
        (not-train-blocked-at t6 p22)
        (not-train-blocked-at t6 p23)
        (not-train-blocked-at t7 p24)
        (not-train-blocked-at t7 p25)
        (not-train-blocked-at t7 p26)
        (not-train-blocked-at t8 p27)
        (not-train-blocked-at t8 p28)
        (not-train-blocked-at t8 p29)
        (not-train-blocked-at t8 p30)
        (not-train-blocked-at t8 p31)
        (not-train-blocked-at t8 p32)

        ;; Boarding points
        (boarding-point t1 p1)
        (boarding-point t2 p4)
        (boarding-point t3 p8)
        (boarding-point t4 p11)
        (boarding-point t5 p17)
        (boarding-point t6 p20)
        (boarding-point t7 p25)
        (boarding-point t8 p30)

        ;; Train speeds
        (= (train-speed t1) 1.0)
        (= (train-speed t2) 1.0)
        (= (train-speed t3) 1.0)
        (= (train-speed t4) 1.0)
        (= (train-speed t5) 1.0)
        (= (train-speed t6) 1.0)
        (= (train-speed t7) 1.0)
        (= (train-speed t8) 1.0)

        ;; Road distances
        (= (road-distance p0 p1) 10)
        (= (road-distance p1 p0) 10)
        (= (road-distance p1 p2) 7)
        (= (road-distance p2 p1) 7)
        (= (road-distance p3 p4) 10)
        (= (road-distance p4 p3) 10)
        (= (road-distance p4 p5) 5)
        (= (road-distance p5 p4) 5)
        (= (road-distance p5 p6) 10)
        (= (road-distance p6 p5) 10)
        (= (road-distance p7 p8) 5)
        (= (road-distance p8 p7) 5)
        (= (road-distance p8 p9) 5)
        (= (road-distance p9 p8) 5)
        (= (road-distance p10 p11) 9)
        (= (road-distance p11 p10) 9)
        (= (road-distance p11 p12) 6)
        (= (road-distance p12 p11) 6)
        (= (road-distance p13 p14) 9)
        (= (road-distance p14 p13) 9)
        (= (road-distance p14 p15) 7)
        (= (road-distance p15 p14) 7)
        (= (road-distance p15 p16) 5)
        (= (road-distance p16 p15) 5)
        (= (road-distance p16 p17) 6)
        (= (road-distance p17 p16) 6)
        (= (road-distance p17 p18) 10)
        (= (road-distance p18 p17) 10)
        (= (road-distance p19 p20) 6)
        (= (road-distance p20 p19) 6)
        (= (road-distance p20 p21) 6)
        (= (road-distance p21 p20) 6)
        (= (road-distance p21 p22) 7)
        (= (road-distance p22 p21) 7)
        (= (road-distance p22 p23) 5)
        (= (road-distance p23 p22) 5)
        (= (road-distance p24 p25) 7)
        (= (road-distance p25 p24) 7)
        (= (road-distance p25 p26) 7)
        (= (road-distance p26 p25) 7)
        (= (road-distance p27 p28) 9)
        (= (road-distance p28 p27) 9)
        (= (road-distance p28 p29) 5)
        (= (road-distance p29 p28) 5)
        (= (road-distance p29 p30) 8)
        (= (road-distance p30 p29) 8)
        (= (road-distance p30 p31) 5)
        (= (road-distance p31 p30) 5)
        (= (road-distance p31 p32) 9)
        (= (road-distance p32 p31) 9)
        (= (road-distance p1 p33) 10)
        (= (road-distance p33 p1) 10)
        (= (road-distance p4 p33) 9)
        (= (road-distance p33 p4) 9)
        (= (road-distance p8 p34) 7)
        (= (road-distance p34 p8) 7)
        (= (road-distance p11 p34) 9)
        (= (road-distance p34 p11) 9)
        (= (road-distance p17 p35) 6)
        (= (road-distance p35 p17) 6)
        (= (road-distance p20 p35) 10)
        (= (road-distance p35 p20) 10)
        (= (road-distance p25 p36) 5)
        (= (road-distance p36 p25) 5)
        (= (road-distance p30 p36) 5)
        (= (road-distance p36 p30) 5)
        (= (road-distance p14 p37) 7)
        (= (road-distance p37 p14) 7)
        (= (road-distance p5 p38) 6)
        (= (road-distance p38 p5) 6)
        (= (road-distance p6 p39) 8)
        (= (road-distance p39 p6) 8)

        ;; Board times
        (= (board-time t1 p1) 1)
        (= (board-time t2 p4) 1)
        (= (board-time t3 p8) 1)
        (= (board-time t4 p11) 1)
        (= (board-time t5 p17) 1)
        (= (board-time t6 p20) 1)
        (= (board-time t7 p25) 1)
        (= (board-time t8 p30) 1)

        ;; Turnout time
        (= (turnout-time) 1)
    )

    (:goal (and
        (train-at t1 p2)
        (train-at t2 p6)
        (train-at t3 p9)
        (train-at t4 p12)
        (train-at t5 p18)
        (train-at t6 p23)
        (train-at t7 p26)
        (train-at t8 p32)
        (board-passengers t1 p1)
        (board-passengers t2 p4)
        (board-passengers t3 p8)
        (board-passengers t4 p11)
        (board-passengers t5 p17)
        (board-passengers t6 p20)
        (board-passengers t7 p25)
        (board-passengers t8 p30)
    ))

    (:metric minimize (total-time))
)